# Docker compose for web app

services:
  web-app:
    image: admin-boilerplate:1.8
    container_name: sawtooth-web-app
    expose:
      - 3000
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./admin-boilerplate:/admin-boilerplate
    working_dir: /admin-boilerplate/packages/admin-boilerplate
    entrypoint: "yarn start"
