# Docker compose for IPFS and Cryptography

services:
  cryptoipfs:
    image: $CRYPTO_IPFS_IMAGE
    container_name: $CRYPTO_IPFS_CONTAINER_NAME
    ports:
      - "5000:5000"
    volumes:
      - $CRYPTO_IPFS_DIR:/home/charmcrypto/charm/charm-dev/HSEABE
    working_dir: /home/charmcrypto/charm/charm-dev/HSEABE
    tty: true
    # make && pip install . && python samples/main.py
    # entrypoint: "python3 utils/crypto-flask.py"
