services:
  ################################################
  ## Cluster PEER 0 ##############################
  ################################################

  ipfs0:
    container_name: ipfs0
    image: ipfs/go-ipfs:v0.7.0
    #   ports:
    #     - "4001:4001" # ipfs swarm - expose if needed/wanted
    #     - "5001:5001" # ipfs api - expose if needed/wanted
    #     - "8080:8080" # ipfs gateway - expose if needed/wanted
    volumes:
      - ./compose/ipfs0:/data/ipfs

  cluster0:
    container_name: cluster0
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs0
    environment:
      CLUSTER_PEERNAME: cluster0
      CLUSTER_SECRET: NEITHNAHT # From shell variable if set
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs0/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: "*" # Trust all peers in Cluster
      CLUSTER_RESTAPI_HTTPLISTENMULTIADDRESS: /ip4/0.0.0.0/tcp/9094 # Expose API
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    ports:
      # Open API port (allows ipfs-cluster-ctl usage on host)
      - "127.0.0.1:9094:9094"
      # The cluster swarm port would need  to be exposed if this container
      # was to connect to cluster peers on other hosts.
      # But this is just a testing cluster.
      # - "9096:9096" # Cluster IPFS Proxy endpoint
    volumes:
      - ./compose/cluster0:/data/ipfs-cluster
  #######################################################
  ## Cluster PEER 1 ####################################
  #######################################################

  ipfs1:
    container_name: ipfs1
    image: ipfs/go-ipfs:v0.7.0
    volumes:
      - ./compose/ipfs1:/data/ipfs

  cluster1:
    container_name: cluster1
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs1
    environment:
      CLUSTER_PEERNAME: cluster1
      CLUSTER_SECRET: NEITHNAHT
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs1/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: "*"
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster1:/data/ipfs-cluster
  #######################################################
  ## Cluster PEER 2 ####################################
  #######################################################

  ipfs2:
    container_name: ipfs2
    image: ipfs/go-ipfs:v0.7.0
    volumes:
      - ./compose/ipfs2:/data/ipfs

  cluster2:
    container_name: cluster2
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs2
    environment:
      CLUSTER_PEERNAME: cluster2
      CLUSTER_SECRET: NEITHNAHT
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs2/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: "*"
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster2:/data/ipfs-cluster
  #######################################################
  ## Cluster PEER 3 ####################################
  #######################################################

  ipfs3:
    container_name: ipfs3
    image: ipfs/go-ipfs:v0.7.0
    volumes:
      - ./compose/ipfs3:/data/ipfs

  cluster3:
    container_name: cluster3
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs3
    environment:
      CLUSTER_PEERNAME: cluster3
      CLUSTER_SECRET: NEITHNAHT
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs3/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: "*"
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster3:/data/ipfs-cluster
  #######################################################
  ## Cluster PEER 4 ####################################
  #######################################################

  ipfs4:
    container_name: ipfs4
    image: ipfs/go-ipfs:v0.7.0
    volumes:
      - ./compose/ipfs4:/data/ipfs

  cluster4:
    container_name: cluster4
    image: ipfs/ipfs-cluster:latest
    depends_on:
      - ipfs4
    environment:
      CLUSTER_PEERNAME: cluster4
      CLUSTER_SECRET: NEITHNAHT
      CLUSTER_IPFSHTTP_NODEMULTIADDRESS: /dns4/ipfs4/tcp/5001
      CLUSTER_CRDT_TRUSTEDPEERS: "*"
      CLUSTER_MONITORPINGINTERVAL: 2s # Speed up peer discovery
    volumes:
      - ./compose/cluster4:/data/ipfs-cluster
